"""
**AI Disclaimer**
This code was generated by Google Gemini through an iterative process.
The code was reviewed and tested for accuracy.
The `simplify_equation` function returns the `best_path` so the final
answer can be easily verified to be a solution.
"""

import sympy as sp
import re
import heapq
import sys

def calculate_complexity(expr_str, num_complexity=1, debug=False):
    """
    Evaluates the "messiness" of an equation.
    Complexity = 1 for each variable and operator.
    Numerical floats/integers have a configurable complexity (default is 1).
    """
    # 1. Standardize exponents. Convert c4**2 to c4*c4 so token counts accurately 
    # reflect the hidden multiplication in powers.
    clean_str = re.sub(r'([a-zA-Z0-9_]+)\*\*([0-9]+)', 
                       lambda m: '*'.join([m.group(1)] * int(m.group(2))), 
                       expr_str)
    clean_str = clean_str.replace(" ", "")
    
    # 2. Enforce the Unary Variable Penalty. 
    # The Lookbehind (?<![\w.)]) ensures we ONLY hit a unary minus, not subtraction like x-t.
    # This expands "-t" to "-1*t", forcing it to cost 5 tokens instead of 2.
    clean_str = re.sub(r'(?<![\w.)])-([a-zA-Z_][a-zA-Z0-9_]*)', r'-1*\1', clean_str)
    
    tokens = []
    i = 0
    n = len(clean_str)
    # Start assuming we are at an operator so a leading "-" is treated as a negative number
    prev_is_op_or_paren = True 
    
    # 3. Tokenize the string by reading left-to-right
    while i < n:
        c = clean_str[i]
        
        # Parentheses don't add to algebraic complexity score
        if c in "()":
            prev_is_op_or_paren = (c == '(')
            i += 1
            continue
            
        if c in "+-*/":
            # Handle unary minus (negative numbers) correctly
            if c == '-' and prev_is_op_or_paren:
                match = re.match(r'-\d+(\.\d+)?([eE][+-]?\d+)?', clean_str[i:])
                if match:
                    tokens.append(match.group())
                    i += len(match.group())
                    prev_is_op_or_paren = False
                    continue
                else:
                    tokens.append(c)
                    prev_is_op_or_paren = True
                    i += 1
            else:
                tokens.append(c) # Standard operator
                prev_is_op_or_paren = True
                i += 1
        else:
            # Match variable names (c3, x) or positive numbers
            match = re.match(r'[a-zA-Z_][a-zA-Z0-9_]*|\d+(\.\d+)?([eE][+-]?\d+)?', clean_str[i:])
            if match:
                tokens.append(match.group())
                i += len(match.group())
                prev_is_op_or_paren = False
            else:
                i += 1 
                
    # 4. Calculate score based on token type
    score = 0
    for token in tokens:
        # If the token is purely a number (integer or float, optionally negative)
        if re.fullmatch(r'-?\d+(\.\d+)?([eE][+-]?\d+)?', token):
            score += num_complexity
        else:
            score += 1

    if debug:
        print(f"\n[DEBUG Complexity] Tokens ({len(tokens)} | Score: {score}): {tokens}")
        
    return score

def format_final_string(expr):
    """
    Cleans up SymPy's internal formatting before returning to the user.
    Uses a custom tree-walker to defeat SymPy's lexicographical sorting (alphabetizing),
    forcing positive terms to the front to prevent "-t + x" formatting penalties.
    """
    def order_positive_first(node):
        # Base case: if it's a simple variable or number, return it as-is
        if not getattr(node, 'args', []):
            return node
        
        # Recursively walk down the expression tree
        new_args = [order_positive_first(arg) for arg in node.args]
        
        # If the node is an Addition block, separate and reorder the terms
        if node.is_Add:
            pos = [a for a in new_args if not a.could_extract_minus_sign()]
            neg = [a for a in new_args if a.could_extract_minus_sign()]
            # evaluate=False locks the exact order so SymPy doesn't re-alphabetize them
            return sp.Add(*(pos + neg), evaluate=False)
        
        # Reconstruct non-addition nodes normally
        try:
            return node.func(*new_args)
        except Exception:
            return node

    # Apply the custom sorting and print strictly without SymPy re-ordering it
    ordered_expr = order_positive_first(expr)
    expr_str = sp.sstr(ordered_expr, order='none').replace(" ", "")
    
    # Expand exponents and unary variables in the final string representation
    expr_str = re.sub(r'([a-zA-Z0-9_]+)\*\*([0-9]+)', 
                      lambda m: '*'.join([m.group(1)] * int(m.group(2))), 
                      expr_str)
    expr_str = re.sub(r'(?<![\w.)])-([a-zA-Z_][a-zA-Z0-9_]*)', r'-1*\1', expr_str)
    
    return expr_str

def safe_is_zero(expr):
    """
    A mathematical safety net. SymPy sometimes returns 'None' instead of True/False 
    when evaluating complex floats. This forces a definitive boolean.
    """
    if expr == 0: return True
    if hasattr(expr, 'is_zero') and expr.is_zero is True: return True
    return False

def map_coefficients(coeffs_list, active_consts, next_idx, debug=False):
    """
    The "Memory" of the script. Checks new sub-expressions and replaces them 
    with sequenced constants (c5, c6) while respecting mathematical relationships.
    """
    new_mappings = {}
    mapped_coeffs = []
    
    for c in coeffs_list:
        c = sp.simplify(c)
        
        # If the term has no unknown constants (e.g., it's just 'x' or '0.5'), ignore it
        if not c.has(*active_consts):
            mapped_coeffs.append(c)
            continue
            
        matched = False
        # Compare against constants we've ALREADY created in this specific iteration
        for mapped_c, symbol in new_mappings.items():
            try:
                if safe_is_zero(sp.simplify(c - mapped_c)):      # Exact match
                    mapped_coeffs.append(symbol)
                    matched = True; break
                elif safe_is_zero(sp.simplify(c + mapped_c)):    # Exact negative
                    mapped_coeffs.append(-symbol)
                    matched = True; break
                elif safe_is_zero(sp.simplify(c * mapped_c - 1)): # Exact reciprocal (t/c3 vs c3/t)
                    mapped_coeffs.append(1/symbol)
                    matched = True; break
                elif safe_is_zero(sp.simplify(c * mapped_c + 1)): # Negative reciprocal
                    mapped_coeffs.append(-1/symbol)
                    matched = True; break
            except Exception:
                pass
                
        # If it doesn't match anything seen yet, generate a brand new constant (c_next)
        if not matched:
            new_sym = sp.Symbol(f'c{next_idx}')
            new_mappings[c] = new_sym
            mapped_coeffs.append(new_sym)
            next_idx += 1
            
    return mapped_coeffs, new_mappings, next_idx

def reconstruct_poly(coeffs, degree, x):
    """
    Takes an array of clean coefficients and rebuilds an algebraic equation.
    E.g., [c5, 0, 1/c6] with degree 2 -> c5*x**2 + 1/c6.
    """
    terms = []
    for i, c in enumerate(coeffs):
        deg = degree - i
        if not safe_is_zero(c):
            # Float contagion fix: prevents SymPy from secretly converting x into 1.0*x
            if c == 1.0: c = sp.Integer(1)
            elif c == -1.0: c = sp.Integer(-1)
            
            if deg == 0: terms.append(c)
            elif deg == 1: terms.append(c * x)
            else: terms.append(c * sp.Pow(x, deg, evaluate=False))
            
    # Return the summed terms, or 0 if everything cancelled out
    return sp.Add(*terms) if terms else sp.Integer(0)

def simplify_equation(expr_str, max_iterations=150, num_complexity=1, debug=False):
    """Main Priority-Queue (Best-First Search) algorithm for equation simplification."""
    
    # 1. Initial Setup & Budgeting
    x, t = sp.symbols('x t')
    expr_str_clean = expr_str.replace('^', '**')
    initial_expr = sp.sympify(expr_str_clean)
    start_score = calculate_complexity(expr_str_clean, num_complexity=num_complexity, debug=debug)
    
    # Dynamically locate all 'c' constants provided in the initial string
    initial_consts = {s for s in initial_expr.free_symbols if str(s).startswith('c') and s not in (x, t)}
    
    # Budget strictly set to the number of original constants in the expression
    max_allowed_consts = len(initial_consts)
    
    # Calculate start_idx: find highest 'c' index and add 1
    existing_indices = [int(str(c)[1:]) for c in initial_consts if str(c)[1:].isdigit()]
    # Setting the array fallback to [5] guarantees max() + 1 will ALWAYS be >= 6
    start_idx = max(existing_indices + [5]) + 1 

    # 2. Priority Queue Setup
    state_id = 0
    pq = [] # Sorted automatically by our complexity score
    visited = set() # Keeps track of strings to avoid infinite duplicate loops
    
    # Global leaderboard to track the absolute best equation found so far
    best_expr = initial_expr
    best_score = calculate_complexity(str(initial_expr), num_complexity=num_complexity)
    best_const_count = max_allowed_consts
    best_path = [format_final_string(initial_expr)]

    def push_state(expr, active_set, current_path):
        """Helper (The 'Bouncer') to score, validate, and add new equations to the queue."""
        nonlocal state_id, best_expr, best_score, best_const_count, best_path
        
        # Quarantine math errors (e.g. divide by zero artifacts)
        if expr.has(sp.nan, sp.zoo, sp.oo, -sp.oo): return
            
        str_rep = format_final_string(expr)
        if str_rep in visited: return
        visited.add(str_rep)
        
        # Rule check: Total constants cannot increase above budget
        current_const_count = len([c for c in active_set if expr.has(c)])
        if current_const_count > max_allowed_consts: return
        
        score = calculate_complexity(str_rep, num_complexity=num_complexity)
        new_path = current_path + [str_rep]
        
        # Push into priority queue. 'score' is first, so it sorts lowest-to-highest.
        heapq.heappush(pq, (score, current_const_count, len(str_rep), state_id, expr, active_set, new_path))
        state_id += 1
        
        # Update the global best equation leaderboard
        if score < best_score or (score == best_score and current_const_count < best_const_count):
            best_expr = expr
            best_score = score
            best_const_count = current_const_count
            best_path = new_path

    # Seed the search with the starting equation
    push_state(initial_expr, initial_consts, [])

    # 3. Main State-Space Search Loop
    iterations = 0
    while pq and iterations < max_iterations:
        iterations += 1
        
        # Print a live-updating status bar in the console
        if not debug:
            sys.stdout.write(f"\r[Progress] Iteration {iterations}/{max_iterations} | Queue: {len(pq):<4} | Best: {best_score:<3}")
            sys.stdout.flush()
        
        # Pop the mathematically simplest equation available
        _, current_const_count, _, _, curr_expr, curr_active, curr_path = heapq.heappop(pq)
        
        try:
            # Convert to Rational Fraction and extract polynomial coefficients
            frac = sp.cancel(curr_expr)
            num, den = frac.as_numer_denom()
            num_poly = sp.Poly(num, x)
            den_poly = sp.Poly(den, x)
            num_coeffs = num_poly.all_coeffs()
            den_coeffs = den_poly.all_coeffs()
            
            # Identify purely symbolic parts of coefficients to use as Division Pivots
            # Explicitly include 1 and -1 to test sign-flipping the entire fraction
            pivots = set([sp.Integer(1), sp.Integer(-1)])
            for c in num_coeffs + den_coeffs:
                if not safe_is_zero(c):
                    # Separate floats from algebra to prevent float precision decay (0.09 * c3 -> c3)
                    indep, dep = c.as_independent(*curr_active, t, as_Add=False)
                    if dep != 1 and dep != -1: 
                        pivots.add(dep)         # Algebraic pivot
                        pivots.add(1/dep)       # Reciprocal pivot
                        pivots.add(-dep)        # Negative algebraic pivot
                        pivots.add(-1/dep)      # Negative reciprocal pivot
            
            # 4. Execute Pivot Moves
            for P in pivots:
                if safe_is_zero(P): continue
                
                # Divide numerator and denominator by Pivot
                new_num_c = [sp.simplify(c / P) for c in num_coeffs]
                new_den_c = [sp.simplify(c / P) for c in den_coeffs]
                
                # Map the resulting messy coefficient blocks to new constant variables
                mapped_combined, new_mappings, _ = map_coefficients(new_num_c + new_den_c, curr_active, start_idx, debug)
                mapped_num = mapped_combined[:len(new_num_c)]
                mapped_den = mapped_combined[len(new_num_c):]
                
                # Reconstruct the fraction
                num_expr = reconstruct_poly(mapped_num, num_poly.degree(), x)
                den_expr = reconstruct_poly(mapped_den, den_poly.degree(), x)
                new_expr = num_expr / den_expr
                
                # Enforce the 't' Rule: If 't' was absorbed into a new constant, 
                # it CANNOT still be free-floating elsewhere in the equation.
                t_was_mapped = any(t in cluster.free_symbols for cluster in new_mappings.keys())
                t_still_present = new_expr.has(t)
                if t_was_mapped and t_still_present: continue 
                    
                # Hand the new equation to the Bouncer
                push_state(new_expr, set(new_mappings.values()), curr_path)
                
        except sp.polys.polyerrors.PolynomialError:
            pass # Triggers if the equation temporarily structurally breaks rational fraction rules
            
        # Perform standard SymPy basic formatting passes as fallback macro-moves
        push_state(sp.cancel(curr_expr), curr_active, curr_path)
        push_state(sp.expand(curr_expr), curr_active, curr_path)
        push_state(sp.factor(curr_expr), curr_active, curr_path)

    # Clear progress bar
    if not debug:
        sys.stdout.write("\r" + " " * 80 + "\r")
        sys.stdout.flush()

    # 5. The "Do No Harm" Fallback Gate
    # If the algorithm failed to find a better equation, reject SymPy's formatting 
    # entirely and return the exact original string provided by the user.
    if best_score > start_score or (best_score == start_score and best_const_count >= max_allowed_consts):
        final_output = format_final_string(expr_str_clean)
        clean_path = [final_output]
        print(f"\n[ Input ]       {expr_str}")
        print(f"[ Complexity ]  Start: {start_score}  |  End: {start_score}  |  Num Weight: {num_complexity}")
        print("\n--- Optimum Path Steps ---")
        print("No simplification possible.")
        print("--------------------------")
        print(f"[ Output ]      {final_output}")
        print("=" * 50)
        return final_output, start_score, best_score, clean_path

    # 6. Final Output Generation
    final_output = format_final_string(best_expr)
    
    # Clean up sequential identical steps in the log
    clean_path = []
    for step in best_path:
        if not clean_path or clean_path[-1] != step:
            clean_path.append(step)

    # Console outputs for ease of verification
    print(f"\n[ Input ]       {expr_str}")
    print(f"[ Complexity ]  Start: {start_score}  |  End: {best_score}  |  Num Weight: {num_complexity}")
    print("\n--- Optimum Path Steps ---")
    for step in clean_path:
        print(step)
    print("--------------------------")
    print(f"[ Output ]      {final_output}")
    print("=" * 50)
    
    # Return both the final string and the list of steps
    return final_output, start_score, best_score, clean_path
